### PR TITLE
Swap pry-debugger for pry-byebug and add readme badges

### PR DESCRIPTION
**Pull request by tas50**
Pry-debugger hasn't been updated for Ruby 2+ and their Github site recommends using pry-byebug for Ruby 2+.  This also adds rubygem and travis badges.  While I was in here I updated getchef.com -> chef.io and fixed the contributing URL.

### CODE REVIEW

**Comment by tas50** [comment]
@chef/client-windows Can I get a review / merge on this change.

**Comment by mwrock** [comment]
I love pry-byebug :+1:

**Comment by ksubrama** [comment]
:+1:

**Comment by btm** [comment]
sure pal :+1:

**Pull request merged**
